import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <div className="bg-neutral-900 w-full h-full p-3 border-b border-green-500 flex items-center justify-between">
        <div>
          <h2 className="text-green-500 font-mono">AlCommit</h2>
        </div>
        <div className="flex">
          <button className="bg-green-500 text-neutral-900 font-mono px-3 py-1 rounded-md hover:bg-green-600 transition-colors mr-4 cursor-pointer">
            <img src='/images/assets/terminal.png' alt="Terminal" className="inline-block w-5 h-5 mr-2" />
            Terminal
          </button>
          <img src='/images/assets/configs.png' alt="Settings" className="w-5 h-5 cursor-pointer mt-1.5 mr-4" />
          <img src='/images/assets/exit.png' alt="Exit" className="w-5 h-5 cursor-pointer mt-1.5" />
        </div>
      </div>
        {children}
      </body>
    </html>
  );
}
